### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by chenshenhai** [idrawjs/studio#14]
## Feature
* [x] move up/down element
* [x] drag element to change index
* [x] html rich-editor
* [x] dark theme
* [x] Export result to Image
* [x] Export result to resource JSON
* [x] Import data from json by upload
* [x] Controll scroll bar by keyon keyboard
* [x] Edit text on screen
